Setup:
  Basic Setup:
    Network Setup:
      Router IP:
        Local IP Address: 192.168.1.3/18
Wireless:
  Basic Settings:
    2.4 GHz:
      Radio Mode: Repeater Bridge
      Service Set Identifier (SSID): ${24gSSID}-Backhaul
      Virtual Interfaces:
        Wireless Interface:
          Service Set Identifier (SSID): ${24gSSID}
          SSID Broadcast: Enable
